### ISSUE TITLE
The userinfo properties should be username, password

### ISSUE THREAD

**Issue by geimbar** [chenkie/aurelia-jwt-auth#1]
In signup.js
var userInfo = { email: this.email, password: this.password }

should be:
var userInfo = { username: this.email, password: this.password }

to be in sync with the user-routes.js in the server.

**Comment by vincentleeuwen** [comment]
+1

**Comment by ncahoon** [comment]
+1

**Comment by chenkie** [comment]
Updated the submodule to the latest commit for the server code. This should solve the issue :)
